spring:
#数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/consumer?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: consumer-user
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8200


eureka:
  instance:
    prefer-ip-address: true #注册服务时使用服务IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true #服务地址
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'

#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.bishe.consumer.entity
  config-location: classpath:mybatis-config.xml




#redis
redis:
  host: 127.0.0.1
  port: 6379
#  连接超时时间
  timeout: 10
  poolMaxTotal: 1000
#  最大空闲
  poolMaxIdle: 500
#  最大等待时间
  poolMaxWait: 500

