server:
  port: 8002
spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      encoding: utf-8
      enabled: true
      mode: HTML
      servlet:
        content-type: text/html
#数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/car?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: hunter


eureka:
  instance:
    prefer-ip-address: true #注册服务时使用服务IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务地址

#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.bishe.hunter.entity
  config-location: classpath:mybatis-config.xml


bishe:
  security:
    browser:
      loginPage: templates/demo.html